// .agent/skills/sci-notebook/examples/react-setup.tsx
import React, { useState } from 'react';
import { SciNotebook } from '@velo-sci/notebook-react';
import '@velo-sci/notebook-core/styles/index.css';

const initialData = {
  id: 'doc-1',
  title: 'Untitled Notebook',
  version: 1,
  cells: [
    { id: '1', type: 'markdown', source: '# Hello Sci-Notebook', metadata: {} },
    { id: '2', type: 'code', source: 'console.log("Executable cell");', metadata: { language: 'javascript' } }
  ]
};

export function NotebookApp() {
  const [notebook, setNotebook] = useState(initialData);

  const handleSave = async (updatedNotebook) => {
    setNotebook(updatedNotebook);
    // Pretend to save to a database
    await fetch('/api/notebooks/' + updatedNotebook.id, {
        method: 'POST',
        body: JSON.stringify(updatedNotebook)
    });
  };

  return (
    <div className="editor-layout">
      <SciNotebook
        notebook={notebook}
        onChange={handleSave}
        theme="dark"
        readOnly={false}
      />
    </div>
  );
}

// .agent/skills/sci-notebook/examples/vue-setup.vue
<script setup>
import { ref } from 'vue';
import { SciNotebook } from '@velo-sci/notebook-vue';
import '@velo-sci/notebook-core/styles/index.css';

const notebook = ref({
  id: 'doc-1',
  version: 1,
  cells: [
    { id: 'c1', type: 'markdown', source: 'Vue Integration', metadata: {} }
  ]
});

function handleNotebookChange(updatedData) {
  notebook.value = updatedData;
}
</script>

<template>
  <div class="editor-container" style="height: 100vh;">
    <!-- Vue wrapper maps onChange to component events or v-model depending on implementation -->
    <SciNotebook 
      :notebook="notebook" 
      @change="handleNotebookChange" 
      theme="light" 
    />
  </div>
</template>
